path_template_model: '../opensim_templates/model_template/Unrestricted_Full_Body_Model.osim'
path_template_scaling_settings: '../opensim_templates/template_scaling_settings.xml'
imu_samplerate: 100
process_subjects:
  - neves
  - julia
process_exercises:
  - ng
  - rd